@HoodieStatsApi_HostAddress = http://localhost:5070

### GET Players
GET {{HoodieStatsApi_HostAddress}}/api/Player
Accept: application/json

### GET ServerStats
GET {{HoodieStatsApi_HostAddress}}/api/serverstats
Accept: application/json

### GET Totel Playtime
GET {{HoodieStatsApi_HostAddress}}/api/stats/totalplaytime
Accept: application/json

### GET server playercount
GET {{HoodieStatsApi_HostAddress}}/api/player/Alex
Accept: application/json

### GET whole Server money volume
GET {{HoodieStatsApi_HostAddress}}/api/player/Alex
Accept: application/json

### GET All Server Hoodies
GET {{HoodieStatsApi_HostAddress}}/api/player/Alex
Accept: application/json