// <auto-generated />
using HoodieStatsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HoodieStatsApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250925204503_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HoodieStatsApi.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Playtime")
                        .HasColumnType("int");

                    b.Property<string>("UUID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("HoodieStatsApi.Models.ServerStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ServerBlocksBroken")
                        .HasColumnType("double");

                    b.Property<double>("ServerBlocksMined")
                        .HasColumnType("double");

                    b.Property<double>("ServerDeaths")
                        .HasColumnType("double");

                    b.Property<double>("ServerEconomy")
                        .HasColumnType("double");

                    b.Property<double>("ServerKills")
                        .HasColumnType("double");

                    b.Property<double>("ServerPlayers")
                        .HasColumnType("double");

                    b.Property<double>("ServerPlaytime")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("ServerStats");
                });
#pragma warning restore 612, 618
        }
    }
}
