// <auto-generated />
using HoodieStatsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HoodieStatsApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HoodieStatsApi.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Playtime")
                        .HasColumnType("int");

                    b.Property<string>("UUID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Steve",
                            Playtime = 120,
                            UUID = "uuid-123"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Alex",
                            Playtime = 250,
                            UUID = "uuid-456"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Herobrine",
                            Playtime = 9999,
                            UUID = "uuid-789"
                        });
                });

            modelBuilder.Entity("HoodieStatsApi.Models.ServerStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ServerBlocksBroken")
                        .HasColumnType("double");

                    b.Property<double>("ServerBlocksMined")
                        .HasColumnType("double");

                    b.Property<double>("ServerDeaths")
                        .HasColumnType("double");

                    b.Property<double>("ServerEconomy")
                        .HasColumnType("double");

                    b.Property<double>("ServerKills")
                        .HasColumnType("double");

                    b.Property<double>("ServerPlayers")
                        .HasColumnType("double");

                    b.Property<double>("ServerPlaytime")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("ServerStats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ServerBlocksBroken = 42000.0,
                            ServerBlocksMined = 50000.0,
                            ServerDeaths = 380.0,
                            ServerEconomy = 15000.5,
                            ServerKills = 450.0,
                            ServerPlayers = 150.0,
                            ServerPlaytime = 3000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
